apiVersion: apps/v1
kind: Deployment
metadata:
  name: knote-java-new
spec:
  replicas: 1
  selector:
    matchLabels:
      app: knote-java-new
  template:
    metadata:
      labels:
        app: knote-java-new
    spec:
      containers:
        - name: knote-java-new
          image: knote-java2
          ports:
            - containerPort: 8080
          env:
            - name: MONGO_URL
              value: mongodb://mongo:27017/dev
          imagePullPolicy: Always
        - name: mongo
          image: mongo:4.4
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_URL
              value: mongodb://mongo:27017/dev
          imagePullPolicy: Always

